### ISSUE TITLE
`dak.concatenate` fails on arrays from `uproot.dask`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#145]
For example:

```python
>>> import uproot, dask_awkward as dak
>>> uproot.__version__
'5.0.2'
>>> dak.__version__
'2023.1.0'
>>> da = uproot.dask('tests/vectors_tree_file.root')
>>> dak.concatenate([da.int_vector_branch, da.int_vector_branch], axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask_awkward/lib/operations.py", line 53, in concatenate
    raise ValueError("All arrays must have identical divisions")
ValueError: All arrays must have identical divisions
```

`da.int_vector_branch.known_divisions` is `False`, which I guess is why it's complaining here, but I don't exactly know what that means. The exact file used is [here](https://github.com/iris-hep/func_adl_uproot/blob/174306406269f7a64df068483c76c566a7c4857a/tests/vectors_tree_file.root), but I think this happens with any `TTree`.

For reference, reading into Awkward Arrays first and running `dak.concatenate` from those does produce the expected result:
```python
>>> a = uproot.open('tests/vectors_tree_file.root:tree').arrays()
>>> da2 = dak.from_awkward(a, 1)
>>> dak.concatenate([da2.int_vector_branch, da2.int_vector_branch], axis=1).compute()
/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask_awkward/lib/core.py:1285: UserWarning: metadata could not be determined; a compute on the first partition will occur.
  warnings.warn(
<Array [[], [-1, 2, 3, -1, 2, 3], [13, 13]] type='3 * var * int32'>
```

**Comment by douglasdavis** [comment]
For `dak.concatenate` to provide a correct result the divisions of the inputs need to be identical, so if the divisions are unknown we fail here. (from_awkward knows the length of the original concrete array so it has known divisions)

This works (because we call the `eager_compute_divisions` method, which will do a compute to determine the length of each partition):

We're getting a warning because `ak.concatenate` is not compatible with typetracer arrays. This will be something we need to report upstream!

```python
>>> import dask_awkward as dak
>>> import uproot
>>> uproot.dask("vectors_tree_file.root")
dask.awkward<from-uproot, npartitions=1>
>>> da = uproot.dask("vectors_tree_file.root")
>>> da.eager_compute_divisions()
>>> concated = dak.concatenate([da.int_vector_branch, da.int_vector_branch], axis=1)
/Users/ddavis/software/repos/dask-awkward/src/dask_awkward/lib/core.py:1285: UserWarning: metadata could not be determined; a compute on the first partition will occur.
  warnings.warn(
>>> concated.compute()
<Array [[], [-1, 2, 3, -1, 2, 3], [13, 13]] type='3 * var * int32'>
```

There are two possible solutions here:
1. uproot.dask should be able to determine the divisions when it instantiates a new `dak.Array` object
2. we can relax the requirement of needing `known_divisions` to be true, and only check that the components getting concatenated have an equal number of partitions (but known length of each). This can cause issues at `compute()` time.
