### ISSUE TITLE
`dak.concatenate` fails on output of `dak.singletons`

### ISSUE THREAD

**Issue by masonproffitt** [dask-contrib/dask-awkward#159]
A trivial example (running on `main` of both `awkward` and `dask-awkward`):

```python
>>> import awkward as ak, dask_awkward as dak
>>> a = ak.Array([[1]])
>>> da = dak.from_awkward(a, 1)
>>> s = dak.singletons(da, axis=1)
>>> dak.concatenate([s], axis=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/iris-hep/src/dask-awkward/src/dask_awkward/lib/operations.py", line 53, in concatenate
    raise ValueError("All arrays must have identical divisions")
ValueError: All arrays must have identical divisions
```

The error is paradoxical, since there's only one array. But the real problem is similar to #145--the divisions are not known:

```python
>>> s.divisions
(None, None)
```

I still don't understand exactly what this means, but this error seems to be a repeating pattern. As in #145, running `s.eager_compute_divisions()` makes this work. Would it make sense for `eager_compute_divisions` to just automatically be run in cases like these? At the very least, the error should explain what to do, but it's quite inconvenient to insert `eager_compute_divisions` everywhere.

**Comment by martindurant** [comment]
`singletons(axis>0)` should maintain the original divisions, I think.

**Comment by martindurant** [comment]
but also we could hav a special case in concatenate to deal with the (not very useful) situation of a single input.

**Comment by douglasdavis** [comment]
Four thoughts

---

> Would it make sense for eager_compute_divisions to just automatically be run in cases like these?

I would argue that we should not run `eager_compute_divisions` whenever necessary because it's going to trigger a compute. The only place I know of right now that runs `eager_compute_divisions` is the `__len__` implementation for the `Array` collection.

---

Something we can in general is add to the error message (we already have our own exception for incompatible partitions that is clearly not used consistently, by its absense from this issue, whoops :)) a note about the existence of `eager_compute_divisions` so people know of a solution to fix that specific problem.

---

For this specific case (`ak.concatenate` raising), I'll reiterate what I said in #145 - I think we can relax the logic to *not* fail before compute if at least the _partitions_ are compatible in cases where the divisions tuple is full of `None`s. In those cases if the total number of partitions happens to be compatible but the divisions are not, that will probably end up in a compute time error (the only thing that scares me is a compute time incorrect result, but I can't think of a case for that off the top of my head right now).

---

I've only experimented for a few minutes but so far I'm not seeing a case of `ak.singletons` that wouldn't satisfy `output_divisions=1` (that is, keep the inputs divisions). This makes sense, right? The function is always just creating new inner lists?
