### ISSUE TITLE
overtouching when re-assigning items into dask_awkward.Array

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#280]
with awkward>=2.2.0, dask_awkward>=2023.5.1, uproot>=5.0.7

```python3
import uproot
import dask_awkward as dak

events = uproot.dask({"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"})

events["WeightXYZW"] = events.MET_pt**2

print(dak.necessary_columns(events.Muon_pt))
```

results in:
```
{'from-uproot-59351be15738a0a09c842e264bf155b9': ['Muon_pt', 'MET_pt']}
```

I'm still not quite sure why did wasn't causing problems in the more strenuous test until now, but this is definitely an issue.

**Comment by lgray** [comment]
From playing around at the typetracer level I can't get this to happen, so I think it's in dask_awkward.

**Comment by lgray** [comment]
Here's the more complex example with data, which requires coffea 2023 and additional latest awkward/dask_awkward/uproot:
[complex_repro.zip](https://github.com/dask-contrib/dask-awkward/files/11710067/complex_repro.zip)

**Comment by Moelf** [comment]
maybe just do a bisect? it should be quick: https://github.com/scikit-hep/awkward/compare/v2.2.1...v2.2.2

**Comment by lgray** [comment]
Indeed: 
- https://github.com/scikit-hep/awkward/pull/2479 is the offending PR
- within that PR it is the following commit: https://github.com/scikit-hep/awkward/pull/2479/commits/19f62aaac1f77c8d8096730f56dead782260d400

@agoose77

**Comment by lgray** [comment]
These may be separate issues, I just can't get a minimal repro (mostly due to time) for the one that's clearly awkward related.

**Comment by lgray** [comment]
Applying https://github.com/scikit-hep/awkward/pull/2520 I am able to remove the regression (although column optimization is a good 2 seconds slower in awkward 2.2.2 as well, so there's a big performance regression in there too)

**Comment by lgray** [comment]
Indeed - these are separate issues.
The `dask_awkward` specific issue here is that unrelated assigned fields are not being optimized away, which should be possible to do with form rehydration.

**Comment by agoose77** [comment]
This can be closed, as it is expected behaviour. 

When loading naively from `uproot` (without form remapping), uproot gives us an outermost `RecordArray` containing (in this case) ragged lists. These ragged lists are considered distinct by the column optimisation routine, because they descend from different columns. As such, touching `MET_pt.__list__` (as required by `with_field`), we have to touch `MET_pt`. 

With form remapping, subfields `Muon_XXX` become `Muon.XXX`, i.e. fields in the same record array, surrounded by an outer list. This remapping gives sufficient information to dask-awkward to understand that the offsets of `MET.xxx` are all shared.

Further, if `MET` and `Muon` are also contained within their own list-of-record array, then it is possible to indicate that `MET.xxx` and `Muon.yyy` share the same offsets too.  This might not be what actually happens in nanoevents, i.e. `Muon` and `MET` might be top-level fields in an root `RecordArray` node, but it's _possible_ for the aforementioned configuration to be the case. 

As such, `with_field` is now behaving as expected, and it is the user side of things that might need some work.

**Comment by lgray** [comment]
Let me check that columns touching hasn't blown up in the torture test in 2.2.4

**Comment by lgray** [comment]
Everything is good! Huzzah!
