### ISSUE TITLE
dak.mask optimization not working

### ISSUE THREAD

**Issue by jrueb** [dask-contrib/dask-awkward#283]
Continuing from #272. There is one remaining issue with the dak.mask optimization.

Optimization of dak.mask when the mask is made using `from_awkward` will fail. The error is
`ValueError: mask must have boolean type, not dtype('float64')` or some similar ValueError (exact error depends on the type of the input array)
and comes from `awkward.mask`.

To reproduce:
```python
import awkward as ak
import dask_awkward as dak


x = ak.Array({"x": [1., 2., 3.]})
ak.to_parquet(x, "masktest.parquet")
x = dak.from_parquet("masktest.parquet")
y = dak.from_awkward(ak.Array([True, True, True]), 1)
z = dak.mask(x["x"], y)
z.compute()
```

The cause is the following code
https://github.com/dask-contrib/dask-awkward/blob/b765938afc963a4e5b8a50f85e59a39c55dfcf21/src/dask_awkward/lib/core.py#L488-L493

This will set the type of the layer for `from_awkward` of the mask (which is a bool array, which a specific compatible structure) to the output of `mask` (which could be much more). When awkward sees this incorrect type of mask, it complains.
Remove the above code makes it working.

**Comment by douglasdavis** [comment]
This code ensures that the blockwise layer has the same metadata as the collection it represents. Unfortunately the order of the layers in the dask highlevel graph are not necessarily descending in order of compute! We were making an incorrect assumption so the last layer in the collection had a metadata that was different from the actual collection's metadata. Should be fixed in #285
