### ISSUE TITLE
`compatible_partitions` between boolean mask and regular array returns `True` if array is sliced while it shouldn't

### ISSUE THREAD

**Issue by iasonkrom** [dask-contrib/dask-awkward#301]
In the following snippet, `compatible_partitions` between a boolean mask and a regular array returns `True` while the array is sliced while it shouldn't.
```python
import uproot
import dask_awkward as dak
from dask_awkward.lib.core import compatible_partitions

fname = "coffea/tests/samples/nano_dy.root"
events = uproot.dask({fname: "Events"})

compatible_partitions(events.Electron_pt[5:], dak.num(events.Electron_pt) == 2)
```

**Comment by douglasdavis** [comment]
Technically these are compatibly partitioned. Only because they have _the same number of partitions_. 

`compatible_partitions` first checks to see if the total number of partitions are the same. If they are not, this would fail. If we haven't failed yet, it checks to see if the `divisions` are the same. But here we run into the case where divisions may not be known. As things stand right now `dak.num(events.Electron_pt) == 2` is not passing down divisions, so the RHS here is telling `compatible_partitions` that it doesn't know it's divisions, just that there is 1 partition. So this check is correctly returning `True` for a case where divisions are uknown for one of the parts of the comparison.

What we really need  to do is implement `divisions` conservation for things like `__eq__`

**Comment by douglasdavis** [comment]
Ah my mistake, it's `dak.num` that is killing the known divisions, not the `__eq__` call (that call is conserving known divisions)

**Comment by douglasdavis** [comment]
will close this now that #303 is in, but it's possible there are still lingering cases out there (of divisions not getting conserved when they should). open another issue if you find one!
