### ISSUE TITLE
Simultaneous compute fails for trivial reproducer

### ISSUE THREAD

**Issue by agoose77** [dask-contrib/dask-awkward#356]
```python
array = ak.Array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])[[0, 2]]
darray = dak.from_awkward(array, 1)
darray_result = darray.map_partitions(identity)

first, second = dask.compute(darray, darray_result)

assert ak.almost_equal(first, second)
assert first.layout.form == second.layout.form
```

**Comment by douglasdavis** [comment]
I think something is going wrong with our layer chain rewrite (that is, sequential blockwise layers getting fused together).

I'll write out the problem, but I don't yet have a solution :) 

If we write 

```python
def identity(x):
    return x

array = ak.Array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])[[0, 2]]
darray = dak.from_awkward(array, 1)
darray_result = darray.map_partitions(identity)
```

then `darray_result` will have 2 layers, the input layer and the map_partitions layer; `darray` will have 1 layer, the input layer:

```pycon
>>> darray.dask
HighLevelGraph with 1 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x11f519f10>
 0. from-awkward-bae3b9f91a2530e3c99b9c39c66e0b6f

>>> darray_result.dask
HighLevelGraph with 2 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x11db00790>
 0. from-awkward-bae3b9f91a2530e3c99b9c39c66e0b6f
 1. identity-621e423f798927192bd16535f7f71502
```

If we simultaneously compute `darray` and `darray_result`; `darray_result` will be rewritten to have a single layer that fuses those two actions

we can short-circuit the failure by simultaneously optimizing first:

```pycon
>>> opt_darray, opt_darray_result = dask.optimize(darray, darray_result)
```

`opt_darray_result` works:

```pycon
>>> opt_darray_result.compute()
<Array [[1, 2, 3], [7, 8, 9]] type='2 * var * int64'>
```

but now `opt_darray` does not:

```
>>> opt_darray.compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ddavis/.pyenv/versions/dev/lib/python3.11/site-packages/dask/base.py", line 342, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddavis/.pyenv/versions/dev/lib/python3.11/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddavis/.pyenv/versions/dev/lib/python3.11/site-packages/dask/local.py", line 304, in nested_get
    return coll[ind]
           ~~~~^^^^^
KeyError: ('from-awkward-bae3b9f91a2530e3c99b9c39c66e0b6f', 0)
```

if we look at the graph structure after optimization we see:

```pycon
>>> opt_darray.dask
HighLevelGraph with 1 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x11f518750>
 0. identity-621e423f798927192bd16535f7f71502

>>> opt_darray_result.dask
HighLevelGraph with 1 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x11f518750>
 0. identity-621e423f798927192bd16535f7f71502
```

They end up getting the exact same graph!

but `opt_darray` still has it's old name:

```
>>> opt_darray.name
'from-awkward-bae3b9f91a2530e3c99b9c39c66e0b6f'
>>> opt_darray_result.name
'identity-621e423f798927192bd16535f7f71502'
```

Since `opt_darray` is _part_ of `opt_darray_result`; the part of `opt_darray_result` that is (correctly) getting overwritten to be of optimal form is (incorrectly) also mutating the original ingredient's graph.

**Comment by douglasdavis** [comment]
(side note: if I turn off the layer chains optimization things do work fine, so it must be the culprit :))

**Comment by martindurant** [comment]
Can we make all our dictionaries debuggable, posting messages like "hey, I've been modified" when mutable actions happen which shouldn't? It would have saved us quite some time...

**Comment by douglasdavis** [comment]
note from chat between @martindurant and me: looks like we need to use the `keys` argument of `__dask_optimize__` to look for all necessary keys and ensure we conserve them.

**Comment by lgray** [comment]
Huh - that's interesting since I have folks computing multiple outputs and not complaining. In any case the fix for this should be in  whatever release we make next.
