### ISSUE TITLE
Missing graph optimization for adding scalars

### ISSUE THREAD

**Issue by alexander-held** [dask-contrib/dask-awkward#499]
Hi, I ran into a setup that derives some scalars and adds those together. It looks like this:
```python
import uproot
import awkward as ak

events = uproot.dask({"https://github.com/scikit-hep/scikit-hep-testdata/"\
    "raw/main/src/skhep_testdata/data/nanoAOD_2015_CMS_Open_Data_ttbar.root": "Events"})

def f(events):
    c = ak.count_nonzero(events["Jet_pt"])
    c += ak.count_nonzero(events["Jet_eta"])
    return c

f(events).visualize(optimize_graph=True)
```
I expected the graph to fully reduce, but it ends up looking like this:
![missing_opt](https://github.com/dask-contrib/dask-awkward/assets/45009355/e4996e2a-0eb3-491f-b07b-62d9e3635b91)

The graph stays the same for `return ak.count_nonzero(events["Jet_pt"]) + ak.count_nonzero(events["Jet_eta"])` (skipping the intermediate `c` variable). @jpivarski suggested a variation:
```python
def f(events):
    return ak.count_nonzero(events["Jet_pt"], axis=1) + ak.count_nonzero(events["Jet_eta"], axis=1)
```
This works and fully reduces into an "add" -> "0" graph as I would expect.

The original intent behind these functions was to read lots of data and transfer as little as possible, hence the accumulation into an integer. Another way this could be accomplished is to wrap the array computed in the previous version once again:
```python
def f(events):
    c = ak.count_nonzero(events["Jet_pt"], axis=1) + ak.count_nonzero(events["Jet_eta"], axis=1)
    return ak.count_nonzero(c)
```
This is attached below. It also doesn't fully reduce, but it at least avoids the large amount of nodes in the original setup. In reality I have O(50) branches, so that original graph quickly explodes.

![aggregate_again](https://github.com/dask-contrib/dask-awkward/assets/45009355/7f14912d-4598-4fc6-a3f4-34254ad9d8d0)

Software versions used:
```
awkward: 2.6.3
dask-awkward: 2024.3.0
uproot: 5.3.2
```

**Comment by lgray** [comment]
Oh I think I see the issue! Each of the `ak.count_nonzero` calls on `axis=0` or `axis=None` is **itself** a tree reduce that cannot be optimized like what you are requesting, where `ak.count_nonzero` on `axis=1` is not a tree reduce since it's embarrasingly parallel rowwise.

So I if you want a small number of tasks you should do:
```python3
def f(events):
    c = ak.count_nonzero(events["Jet_pt"], axis=1) + ak.count_nonzero(events["Jet_eta"], axis=1)
    return ak.count_nonzero(c)
```

and then tree-reduce the entire result of that using `ak.sum(..., axis=0)`.

**Comment by jpivarski** [comment]
Short story: I'm coming to agree with @lgray. `axis=None` reduction is one of those things that's simple on a single computer with shared memory, but it requires data transfers in the distributed data case. (Similar to how `groupby` is a simple operation in Pandas but a big, expensive one in `dask.dataframe`.)

Unfortunately, `axis=None` is also the default (for consistency with NumPy's API), so something that looks simpler in source code is the more complex case.

In general, operations on scalars, such as `scalar + scalar`, should collapse to a single Dask node, but the issue here is that making each `scalar` in that formula requires a tree-reduction.

--------------------

Long story:

`axis=0` and `axis=None` are different. Here's the full picture:

```python
>>> import awkward as ak
>>> array = ak.Array([
...     [  1,   2,   3,    ],
...     [ 10,  20,         ],
...     [100, 200, 300, 400],
... ])
```

The reduction you normally want, `axis=-1` (which in this case is `axis=1`) replaces the innermost lists with scalars:

```python
>>> ak.sum(array, axis=1)
<Array [6, 30, 1000] type='3 * int64'>
```

`axis=0` cuts the other way, vertically instead of horizontally:

```python
>>> ak.sum(array, axis=0)
<Array [111, 222, 303, 400] type='4 * int64'>
```

and `axis=None` turns everything into a single scalar:

```python
>>> ak.sum(array, axis=None)
1036
```

dask-awkward arrays are partitioned in the first dimension only. If the data are 2 (ragged) dimensional, with `axis=0` being the events and `axis=1` being the particles, then each partition is a set of events. Each Dask worker sees a single partition of events, not all of the events. Therefore, to compute the `ak.count_nonzero` reducer with `axis=None` (the default), there needs to be communication across the workers to have each worker send its partial count of non-zero elements to be tallied up into a grand total: that's a tree-reduction, although for data as small as scalars (a few bytes each), I would hope that the tree-reduction is only one level deep.

Then if you take a sum of those scalars,

```python
ak.count_nonzero(events["Jet_pt"]) + ak.count_nonzero(events["Jet_eta"])
```

the `+` has to be _after_ the two tree-reductions. The best it could be is

```mermaid
flowchart TD
    A1[count of Jet_pt part 1]
    A2[part 2]
    A3[part 3]
    A[count of all Jet_pt]
    A1 ---> A
    A2 ---> A
    A3 ---> A
    B1[count of Jet_eta part 1]
    B2[part 2]
    B3[part 3]
    B[count of all Jet_eta]
    B1 ---> B
    B2 ---> B
    B3 ---> B
    C[sum of both count_nonzeros]
    A ---> C
    B ---> C
```

with the first level being the two tree-reductions of `count_nonzero` on `Jet_pt` partitions 1, 2, 3 and `Jet_eta` partitions 1, 2, 3 and the second level adding those results.

* If the query planner is smart enough to realize that tree-reductions of scalars never needs to be more than one level deep, then the top row of arrows is only one row; if the query planner doesn't realize this, it might be multiple rows.
* If the query planner is also smart enough to realize that addition of scalars should require minimal data movement, it could decide to put both tree-reductions on the same Dask worker, so that the sum of two integers is done in memory without having to send the data to another machine. That is, "count of all `Jet_pt`" and "count of all `Jet_eta`" would be on the same machine and there would be no data transfer to "sum of both `count_nonzeros`".

```mermaid
flowchart TD
    A1[count of Jet_pt part 1]
    A2[part 2]
    A3[part 3]
    A[count of all Jet_pt and all Jet_eta]
    B1[count of Jet_eta part 1]
    B2[part 2]
    B3[part 3]
    A1 ---> A
    A2 ---> A
    A3 ---> A
    B1 ---> A
    B2 ---> A
    B3 ---> A
```

So at best, this can be just one row of arrows, one transfer of scalars from Dask workers sitting on each of the many partitions to a single sum. It can't collapse to no arrows.

But `axis=1` reduction can collapse to no arrows:

```mermaid
flowchart TD
    A1[count of Jet_pt per-event, part 1]
    A2[part 2]
    A3[part 3]
    B1[count of Jet_eta per-event, part 1]
    B2[part 2]
    B3[part 3]
```

because `axis=1` reduction is keeping each set of events on the machine where it started. It's not asking for any data movement.

**Comment by jpivarski** [comment]
We concluded that this is a gotcha, not a bug.
